---

- hosts: all
  become: true
  tasks:
    - name: Update the Fedora system
      tags: update
      dnf:
        name: "*"
        state: latest
        update_cache: yes



- hosts: web_server
  become: true
  roles:
    - web_server
